/// GENERATED CODE
/// This file is auto-generated by the 'scrape_icons' script, and should not be modified by hand.
/// See the README.md for more information.
/// Generated on Mon Oct 05 2020 11:14:06 GMT+0300 (Eastern European Summer Time)

import 'package:flutter/material.dart';

import 'package:weather_icons/src/util/wi_data.dart';

/// All of WeatherIcons in the form of static [IconData] variables.
///
/// See [WeatherIcons](https://erikflowers.github.io/weather-icons/) for more info.
///
/// For getting a rotated wind icon, you can use [WindIcon] widget.
///
/// Sample Usage:
///
///     IconButton(
///       icon: new Icon(WeatherIcons.rain),
///       onPressed: () { print("Hello World"); }
///     );
class WeatherIcons {
  /// [IconData] for 'wi-day-sunny' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_sunny = const WIData(0xf00d);

  /// [IconData] for 'wi-day-cloudy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_cloudy = const WIData(0xf002);

  /// [IconData] for 'wi-day-cloudy-gusts' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_cloudy_gusts = const WIData(0xf000);

  /// [IconData] for 'wi-day-cloudy-windy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_cloudy_windy = const WIData(0xf001);

  /// [IconData] for 'wi-day-fog' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_fog = const WIData(0xf003);

  /// [IconData] for 'wi-day-hail' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_hail = const WIData(0xf004);

  /// [IconData] for 'wi-day-haze' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_haze = const WIData(0xf0b6);

  /// [IconData] for 'wi-day-lightning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_lightning = const WIData(0xf005);

  /// [IconData] for 'wi-day-rain' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_rain = const WIData(0xf008);

  /// [IconData] for 'wi-day-rain-mix' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_rain_mix = const WIData(0xf006);

  /// [IconData] for 'wi-day-rain-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_rain_wind = const WIData(0xf007);

  /// [IconData] for 'wi-day-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_showers = const WIData(0xf009);

  /// [IconData] for 'wi-day-sleet' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_sleet = const WIData(0xf0b2);

  /// [IconData] for 'wi-day-sleet-storm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_sleet_storm = const WIData(0xf068);

  /// [IconData] for 'wi-day-snow' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_snow = const WIData(0xf00a);

  /// [IconData] for 'wi-day-snow-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_snow_thunderstorm = const WIData(0xf06b);

  /// [IconData] for 'wi-day-snow-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_snow_wind = const WIData(0xf065);

  /// [IconData] for 'wi-day-sprinkle' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_sprinkle = const WIData(0xf00b);

  /// [IconData] for 'wi-day-storm-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_storm_showers = const WIData(0xf00e);

  /// [IconData] for 'wi-day-sunny-overcast' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_sunny_overcast = const WIData(0xf00c);

  /// [IconData] for 'wi-day-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_thunderstorm = const WIData(0xf010);

  /// [IconData] for 'wi-day-windy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_windy = const WIData(0xf085);

  /// [IconData] for 'wi-solar-eclipse' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData solar_eclipse = const WIData(0xf06e);

  /// [IconData] for 'wi-hot' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData hot = const WIData(0xf072);

  /// [IconData] for 'wi-day-cloudy-high' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_cloudy_high = const WIData(0xf07d);

  /// [IconData] for 'wi-day-light-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_light_wind = const WIData(0xf0c4);

  /// [IconData] for 'wi-night-clear' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_clear = const WIData(0xf02e);

  /// [IconData] for 'wi-night-alt-cloudy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_cloudy = const WIData(0xf086);

  /// [IconData] for 'wi-night-alt-cloudy-gusts' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_cloudy_gusts = const WIData(0xf022);

  /// [IconData] for 'wi-night-alt-cloudy-windy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_cloudy_windy = const WIData(0xf023);

  /// [IconData] for 'wi-night-alt-hail' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_hail = const WIData(0xf024);

  /// [IconData] for 'wi-night-alt-lightning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_lightning = const WIData(0xf025);

  /// [IconData] for 'wi-night-alt-rain' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_rain = const WIData(0xf028);

  /// [IconData] for 'wi-night-alt-rain-mix' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_rain_mix = const WIData(0xf026);

  /// [IconData] for 'wi-night-alt-rain-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_rain_wind = const WIData(0xf027);

  /// [IconData] for 'wi-night-alt-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_showers = const WIData(0xf029);

  /// [IconData] for 'wi-night-alt-sleet' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_sleet = const WIData(0xf0b4);

  /// [IconData] for 'wi-night-alt-sleet-storm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_sleet_storm = const WIData(0xf06a);

  /// [IconData] for 'wi-night-alt-snow' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_snow = const WIData(0xf02a);

  /// [IconData] for 'wi-night-alt-snow-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_snow_thunderstorm = const WIData(0xf06d);

  /// [IconData] for 'wi-night-alt-snow-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_snow_wind = const WIData(0xf067);

  /// [IconData] for 'wi-night-alt-sprinkle' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_sprinkle = const WIData(0xf02b);

  /// [IconData] for 'wi-night-alt-storm-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_storm_showers = const WIData(0xf02c);

  /// [IconData] for 'wi-night-alt-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_thunderstorm = const WIData(0xf02d);

  /// [IconData] for 'wi-night-cloudy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_cloudy = const WIData(0xf031);

  /// [IconData] for 'wi-night-cloudy-gusts' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_cloudy_gusts = const WIData(0xf02f);

  /// [IconData] for 'wi-night-cloudy-windy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_cloudy_windy = const WIData(0xf030);

  /// [IconData] for 'wi-night-fog' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_fog = const WIData(0xf04a);

  /// [IconData] for 'wi-night-hail' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_hail = const WIData(0xf032);

  /// [IconData] for 'wi-night-lightning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_lightning = const WIData(0xf033);

  /// [IconData] for 'wi-night-partly-cloudy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_partly_cloudy = const WIData(0xf083);

  /// [IconData] for 'wi-night-rain' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_rain = const WIData(0xf036);

  /// [IconData] for 'wi-night-rain-mix' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_rain_mix = const WIData(0xf034);

  /// [IconData] for 'wi-night-rain-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_rain_wind = const WIData(0xf035);

  /// [IconData] for 'wi-night-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_showers = const WIData(0xf037);

  /// [IconData] for 'wi-night-sleet' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_sleet = const WIData(0xf0b3);

  /// [IconData] for 'wi-night-sleet-storm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_sleet_storm = const WIData(0xf069);

  /// [IconData] for 'wi-night-snow' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_snow = const WIData(0xf038);

  /// [IconData] for 'wi-night-snow-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_snow_thunderstorm = const WIData(0xf06c);

  /// [IconData] for 'wi-night-snow-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_snow_wind = const WIData(0xf066);

  /// [IconData] for 'wi-night-sprinkle' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_sprinkle = const WIData(0xf039);

  /// [IconData] for 'wi-night-storm-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_storm_showers = const WIData(0xf03a);

  /// [IconData] for 'wi-night-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_thunderstorm = const WIData(0xf03b);

  /// [IconData] for 'wi-lunar-eclipse' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData lunar_eclipse = const WIData(0xf070);

  /// [IconData] for 'wi-stars' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData stars = const WIData(0xf077);

  /// [IconData] for 'wi-storm-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData storm_showers = const WIData(0xf01d);

  /// [IconData] for 'wi-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData thunderstorm = const WIData(0xf01e);

  /// [IconData] for 'wi-night-alt-cloudy-high' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_cloudy_high = const WIData(0xf07e);

  /// [IconData] for 'wi-night-cloudy-high' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_cloudy_high = const WIData(0xf080);

  /// [IconData] for 'wi-night-alt-partly-cloudy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_partly_cloudy = const WIData(0xf081);

  /// [IconData] for 'wi-cloud' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloud = const WIData(0xf041);

  /// [IconData] for 'wi-cloudy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloudy = const WIData(0xf013);

  /// [IconData] for 'wi-cloudy-gusts' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloudy_gusts = const WIData(0xf011);

  /// [IconData] for 'wi-cloudy-windy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloudy_windy = const WIData(0xf012);

  /// [IconData] for 'wi-fog' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData fog = const WIData(0xf014);

  /// [IconData] for 'wi-hail' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData hail = const WIData(0xf015);

  /// [IconData] for 'wi-rain' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData rain = const WIData(0xf019);

  /// [IconData] for 'wi-rain-mix' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData rain_mix = const WIData(0xf017);

  /// [IconData] for 'wi-rain-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData rain_wind = const WIData(0xf018);

  /// [IconData] for 'wi-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData showers = const WIData(0xf01a);

  /// [IconData] for 'wi-sleet' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData sleet = const WIData(0xf0b5);

  /// [IconData] for 'wi-snow' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData snow = const WIData(0xf01b);

  /// [IconData] for 'wi-sprinkle' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData sprinkle = const WIData(0xf01c);

  /// [IconData] for 'wi-snow-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData snow_wind = const WIData(0xf064);

  /// [IconData] for 'wi-smog' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData smog = const WIData(0xf074);

  /// [IconData] for 'wi-smoke' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData smoke = const WIData(0xf062);

  /// [IconData] for 'wi-lightning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData lightning = const WIData(0xf016);

  /// [IconData] for 'wi-raindrops' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData raindrops = const WIData(0xf04e);

  /// [IconData] for 'wi-raindrop' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData raindrop = const WIData(0xf078);

  /// [IconData] for 'wi-dust' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData dust = const WIData(0xf063);

  /// [IconData] for 'wi-snowflake-cold' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData snowflake_cold = const WIData(0xf076);

  /// [IconData] for 'wi-windy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData windy = const WIData(0xf021);

  /// [IconData] for 'wi-strong-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData strong_wind = const WIData(0xf050);

  /// [IconData] for 'wi-sandstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData sandstorm = const WIData(0xf082);

  /// [IconData] for 'wi-earthquake' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData earthquake = const WIData(0xf0c6);

  /// [IconData] for 'wi-fire' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData fire = const WIData(0xf0c7);

  /// [IconData] for 'wi-flood' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData flood = const WIData(0xf07c);

  /// [IconData] for 'wi-meteor' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData meteor = const WIData(0xf071);

  /// [IconData] for 'wi-tsunami' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData tsunami = const WIData(0xf0c5);

  /// [IconData] for 'wi-volcano' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData volcano = const WIData(0xf0c8);

  /// [IconData] for 'wi-hurricane' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData hurricane = const WIData(0xf073);

  /// [IconData] for 'wi-tornado' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData tornado = const WIData(0xf056);

  /// [IconData] for 'wi-small-craft-advisory' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData small_craft_advisory = const WIData(0xf0cc);

  /// [IconData] for 'wi-gale-warning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData gale_warning = const WIData(0xf0cd);

  /// [IconData] for 'wi-storm-warning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData storm_warning = const WIData(0xf0ce);

  /// [IconData] for 'wi-hurricane-warning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData hurricane_warning = const WIData(0xf0cf);

  /// [IconData] for 'wi-wind-direction' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_direction = const WIData(0xf0b1);

  /// [IconData] for 'wi-alien' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData alien = const WIData(0xf075);

  /// [IconData] for 'wi-celsius' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData celsius = const WIData(0xf03c);

  /// [IconData] for 'wi-fahrenheit' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData fahrenheit = const WIData(0xf045);

  /// [IconData] for 'wi-degrees' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData degrees = const WIData(0xf042);

  /// [IconData] for 'wi-thermometer' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData thermometer = const WIData(0xf055);

  /// [IconData] for 'wi-thermometer-exterior' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData thermometer_exterior = const WIData(0xf053);

  /// [IconData] for 'wi-thermometer-internal' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData thermometer_internal = const WIData(0xf054);

  /// [IconData] for 'wi-cloud-down' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloud_down = const WIData(0xf03d);

  /// [IconData] for 'wi-cloud-up' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloud_up = const WIData(0xf040);

  /// [IconData] for 'wi-cloud-refresh' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloud_refresh = const WIData(0xf03e);

  /// [IconData] for 'wi-horizon' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData horizon = const WIData(0xf047);

  /// [IconData] for 'wi-horizon-alt' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData horizon_alt = const WIData(0xf046);

  /// [IconData] for 'wi-sunrise' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData sunrise = const WIData(0xf051);

  /// [IconData] for 'wi-sunset' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData sunset = const WIData(0xf052);

  /// [IconData] for 'wi-moonrise' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moonrise = const WIData(0xf0c9);

  /// [IconData] for 'wi-moonset' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moonset = const WIData(0xf0ca);

  /// [IconData] for 'wi-refresh' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData refresh = const WIData(0xf04c);

  /// [IconData] for 'wi-refresh-alt' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData refresh_alt = const WIData(0xf04b);

  /// [IconData] for 'wi-umbrella' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData umbrella = const WIData(0xf084);

  /// [IconData] for 'wi-barometer' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData barometer = const WIData(0xf079);

  /// [IconData] for 'wi-humidity' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData humidity = const WIData(0xf07a);

  /// [IconData] for 'wi-na' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData na = const WIData(0xf07b);

  /// [IconData] for 'wi-train' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData train = const WIData(0xf0cb);

  /// [IconData] for 'wi-moon-new' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_new = const WIData(0xf095);

  /// [IconData] for 'wi-moon-waxing-crescent-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_crescent_1 = const WIData(0xf096);

  /// [IconData] for 'wi-moon-waxing-crescent-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_crescent_2 = const WIData(0xf097);

  /// [IconData] for 'wi-moon-waxing-crescent-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_crescent_3 = const WIData(0xf098);

  /// [IconData] for 'wi-moon-waxing-crescent-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_crescent_4 = const WIData(0xf099);

  /// [IconData] for 'wi-moon-waxing-crescent-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_crescent_5 = const WIData(0xf09a);

  /// [IconData] for 'wi-moon-waxing-crescent-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_crescent_6 = const WIData(0xf09b);

  /// [IconData] for 'wi-moon-first-quarter' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_first_quarter = const WIData(0xf09c);

  /// [IconData] for 'wi-moon-waxing-gibbous-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_gibbous_1 = const WIData(0xf09d);

  /// [IconData] for 'wi-moon-waxing-gibbous-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_gibbous_2 = const WIData(0xf09e);

  /// [IconData] for 'wi-moon-waxing-gibbous-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_gibbous_3 = const WIData(0xf09f);

  /// [IconData] for 'wi-moon-waxing-gibbous-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_gibbous_4 = const WIData(0xf0a0);

  /// [IconData] for 'wi-moon-waxing-gibbous-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_gibbous_5 = const WIData(0xf0a1);

  /// [IconData] for 'wi-moon-waxing-gibbous-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_gibbous_6 = const WIData(0xf0a2);

  /// [IconData] for 'wi-moon-full' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_full = const WIData(0xf0a3);

  /// [IconData] for 'wi-moon-waning-gibbous-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_gibbous_1 = const WIData(0xf0a4);

  /// [IconData] for 'wi-moon-waning-gibbous-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_gibbous_2 = const WIData(0xf0a5);

  /// [IconData] for 'wi-moon-waning-gibbous-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_gibbous_3 = const WIData(0xf0a6);

  /// [IconData] for 'wi-moon-waning-gibbous-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_gibbous_4 = const WIData(0xf0a7);

  /// [IconData] for 'wi-moon-waning-gibbous-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_gibbous_5 = const WIData(0xf0a8);

  /// [IconData] for 'wi-moon-waning-gibbous-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_gibbous_6 = const WIData(0xf0a9);

  /// [IconData] for 'wi-moon-third-quarter' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_third_quarter = const WIData(0xf0aa);

  /// [IconData] for 'wi-moon-waning-crescent-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_crescent_1 = const WIData(0xf0ab);

  /// [IconData] for 'wi-moon-waning-crescent-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_crescent_2 = const WIData(0xf0ac);

  /// [IconData] for 'wi-moon-waning-crescent-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_crescent_3 = const WIData(0xf0ad);

  /// [IconData] for 'wi-moon-waning-crescent-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_crescent_4 = const WIData(0xf0ae);

  /// [IconData] for 'wi-moon-waning-crescent-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_crescent_5 = const WIData(0xf0af);

  /// [IconData] for 'wi-moon-waning-crescent-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_crescent_6 = const WIData(0xf0b0);

  /// [IconData] for 'wi-moon-alt-new' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_new = const WIData(0xf0eb);

  /// [IconData] for 'wi-moon-alt-waxing-crescent-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_crescent_1 = const WIData(0xf0d0);

  /// [IconData] for 'wi-moon-alt-waxing-crescent-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_crescent_2 = const WIData(0xf0d1);

  /// [IconData] for 'wi-moon-alt-waxing-crescent-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_crescent_3 = const WIData(0xf0d2);

  /// [IconData] for 'wi-moon-alt-waxing-crescent-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_crescent_4 = const WIData(0xf0d3);

  /// [IconData] for 'wi-moon-alt-waxing-crescent-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_crescent_5 = const WIData(0xf0d4);

  /// [IconData] for 'wi-moon-alt-waxing-crescent-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_crescent_6 = const WIData(0xf0d5);

  /// [IconData] for 'wi-moon-alt-first-quarter' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_first_quarter = const WIData(0xf0d6);

  /// [IconData] for 'wi-moon-alt-waxing-gibbous-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_gibbous_1 = const WIData(0xf0d7);

  /// [IconData] for 'wi-moon-alt-waxing-gibbous-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_gibbous_2 = const WIData(0xf0d8);

  /// [IconData] for 'wi-moon-alt-waxing-gibbous-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_gibbous_3 = const WIData(0xf0d9);

  /// [IconData] for 'wi-moon-alt-waxing-gibbous-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_gibbous_4 = const WIData(0xf0da);

  /// [IconData] for 'wi-moon-alt-waxing-gibbous-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_gibbous_5 = const WIData(0xf0db);

  /// [IconData] for 'wi-moon-alt-waxing-gibbous-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_gibbous_6 = const WIData(0xf0dc);

  /// [IconData] for 'wi-moon-alt-full' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_full = const WIData(0xf0dd);

  /// [IconData] for 'wi-moon-alt-waning-gibbous-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_gibbous_1 = const WIData(0xf0de);

  /// [IconData] for 'wi-moon-alt-waning-gibbous-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_gibbous_2 = const WIData(0xf0df);

  /// [IconData] for 'wi-moon-alt-waning-gibbous-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_gibbous_3 = const WIData(0xf0e0);

  /// [IconData] for 'wi-moon-alt-waning-gibbous-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_gibbous_4 = const WIData(0xf0e1);

  /// [IconData] for 'wi-moon-alt-waning-gibbous-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_gibbous_5 = const WIData(0xf0e2);

  /// [IconData] for 'wi-moon-alt-waning-gibbous-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_gibbous_6 = const WIData(0xf0e3);

  /// [IconData] for 'wi-moon-alt-third-quarter' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_third_quarter = const WIData(0xf0e4);

  /// [IconData] for 'wi-moon-alt-waning-crescent-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_crescent_1 = const WIData(0xf0e5);

  /// [IconData] for 'wi-moon-alt-waning-crescent-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_crescent_2 = const WIData(0xf0e6);

  /// [IconData] for 'wi-moon-alt-waning-crescent-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_crescent_3 = const WIData(0xf0e7);

  /// [IconData] for 'wi-moon-alt-waning-crescent-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_crescent_4 = const WIData(0xf0e8);

  /// [IconData] for 'wi-moon-alt-waning-crescent-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_crescent_5 = const WIData(0xf0e9);

  /// [IconData] for 'wi-moon-alt-waning-crescent-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_crescent_6 = const WIData(0xf0ea);

  /// [IconData] for 'wi-time-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_1 = const WIData(0xf08a);

  /// [IconData] for 'wi-time-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_2 = const WIData(0xf08b);

  /// [IconData] for 'wi-time-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_3 = const WIData(0xf08c);

  /// [IconData] for 'wi-time-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_4 = const WIData(0xf08d);

  /// [IconData] for 'wi-time-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_5 = const WIData(0xf08e);

  /// [IconData] for 'wi-time-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_6 = const WIData(0xf08f);

  /// [IconData] for 'wi-time-7' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_7 = const WIData(0xf090);

  /// [IconData] for 'wi-time-8' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_8 = const WIData(0xf091);

  /// [IconData] for 'wi-time-9' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_9 = const WIData(0xf092);

  /// [IconData] for 'wi-time-10' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_10 = const WIData(0xf093);

  /// [IconData] for 'wi-time-11' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_11 = const WIData(0xf094);

  /// [IconData] for 'wi-time-12' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_12 = const WIData(0xf089);

  /// [IconData] for 'wi-direction-up' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_up = const WIData(0xf058);

  /// [IconData] for 'wi-direction-up-right' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_up_right = const WIData(0xf057);

  /// [IconData] for 'wi-direction-right' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_right = const WIData(0xf04d);

  /// [IconData] for 'wi-direction-down-right' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_down_right = const WIData(0xf088);

  /// [IconData] for 'wi-direction-down' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_down = const WIData(0xf044);

  /// [IconData] for 'wi-direction-down-left' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_down_left = const WIData(0xf043);

  /// [IconData] for 'wi-direction-left' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_left = const WIData(0xf048);

  /// [IconData] for 'wi-direction-up-left' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_up_left = const WIData(0xf087);

  /// [IconData] for 'wi-wind-beaufort-0' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_0 = const WIData(0xf0b7);

  /// [IconData] for 'wi-wind-beaufort-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_1 = const WIData(0xf0b8);

  /// [IconData] for 'wi-wind-beaufort-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_2 = const WIData(0xf0b9);

  /// [IconData] for 'wi-wind-beaufort-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_3 = const WIData(0xf0ba);

  /// [IconData] for 'wi-wind-beaufort-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_4 = const WIData(0xf0bb);

  /// [IconData] for 'wi-wind-beaufort-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_5 = const WIData(0xf0bc);

  /// [IconData] for 'wi-wind-beaufort-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_6 = const WIData(0xf0bd);

  /// [IconData] for 'wi-wind-beaufort-7' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_7 = const WIData(0xf0be);

  /// [IconData] for 'wi-wind-beaufort-8' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_8 = const WIData(0xf0bf);

  /// [IconData] for 'wi-wind-beaufort-9' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_9 = const WIData(0xf0c0);

  /// [IconData] for 'wi-wind-beaufort-10' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_10 = const WIData(0xf0c1);

  /// [IconData] for 'wi-wind-beaufort-11' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_11 = const WIData(0xf0c2);

  /// [IconData] for 'wi-wind-beaufort-12' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_12 = const WIData(0xf0c3);

  /// [IconData] for the base wind icon from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  ///
  /// To achieve a rotated wind icon see [WindIcon].
  static const IconData wind = const WIData(0xf0b1);

  /// [IconData] for 'wind-deg-0' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_0 = const WIData(0xf05c);

  /// [IconData] for 'wind-deg-45' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_45 = const WIData(0xf05a);

  /// [IconData] for 'wind-deg-90' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_90 = const WIData(0xf059);

  /// [IconData] for 'wind-deg-135' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_135 = const WIData(0xf05d);

  /// [IconData] for 'wind-deg-180' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_180 = const WIData(0xf060);

  /// [IconData] for 'wind-deg-225' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_225 = const WIData(0xf05e);

  /// [IconData] for 'wind-deg-270' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_270 = const WIData(0xf061);

  /// [IconData] for 'wind-deg-315' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_315 = const WIData(0xf05b);

  /// Get the matching [IconData] from the WeatherIcon name.
  ///
  /// If you do not pass in a [fallback] then it will throw if it cannot find the icon.
  ///
  /// See [WeatherIcons](https://erikflowers.github.io/weather-icons/) for more info.
  ///
  /// Sample Usage:
  ///
  ///     IconButton(
  ///       icon: new Icon(WeatherIcons.fromString('wi-day-sunny')),
  ///       onPressed: () { print("Hello World"); }
  ///     );
  static IconData fromString(
    String name, {
    IconData fallback,
  }) {
    final target = name.replaceAll('_', '-');
    final exists = _all.containsKey(target);
    if (!exists && fallback == null) {
      throw UnsupportedError('Unsupported icon $name, with no fallback');
    }

    return exists ? _all[target] : fallback;
  }

  static const Map<String, IconData> _all = {
    'wi-day-sunny': day_sunny,
    'wi-day-cloudy': day_cloudy,
    'wi-day-cloudy-gusts': day_cloudy_gusts,
    'wi-day-cloudy-windy': day_cloudy_windy,
    'wi-day-fog': day_fog,
    'wi-day-hail': day_hail,
    'wi-day-haze': day_haze,
    'wi-day-lightning': day_lightning,
    'wi-day-rain': day_rain,
    'wi-day-rain-mix': day_rain_mix,
    'wi-day-rain-wind': day_rain_wind,
    'wi-day-showers': day_showers,
    'wi-day-sleet': day_sleet,
    'wi-day-sleet-storm': day_sleet_storm,
    'wi-day-snow': day_snow,
    'wi-day-snow-thunderstorm': day_snow_thunderstorm,
    'wi-day-snow-wind': day_snow_wind,
    'wi-day-sprinkle': day_sprinkle,
    'wi-day-storm-showers': day_storm_showers,
    'wi-day-sunny-overcast': day_sunny_overcast,
    'wi-day-thunderstorm': day_thunderstorm,
    'wi-day-windy': day_windy,
    'wi-solar-eclipse': solar_eclipse,
    'wi-hot': hot,
    'wi-day-cloudy-high': day_cloudy_high,
    'wi-day-light-wind': day_light_wind,
    'wi-night-clear': night_clear,
    'wi-night-alt-cloudy': night_alt_cloudy,
    'wi-night-alt-cloudy-gusts': night_alt_cloudy_gusts,
    'wi-night-alt-cloudy-windy': night_alt_cloudy_windy,
    'wi-night-alt-hail': night_alt_hail,
    'wi-night-alt-lightning': night_alt_lightning,
    'wi-night-alt-rain': night_alt_rain,
    'wi-night-alt-rain-mix': night_alt_rain_mix,
    'wi-night-alt-rain-wind': night_alt_rain_wind,
    'wi-night-alt-showers': night_alt_showers,
    'wi-night-alt-sleet': night_alt_sleet,
    'wi-night-alt-sleet-storm': night_alt_sleet_storm,
    'wi-night-alt-snow': night_alt_snow,
    'wi-night-alt-snow-thunderstorm': night_alt_snow_thunderstorm,
    'wi-night-alt-snow-wind': night_alt_snow_wind,
    'wi-night-alt-sprinkle': night_alt_sprinkle,
    'wi-night-alt-storm-showers': night_alt_storm_showers,
    'wi-night-alt-thunderstorm': night_alt_thunderstorm,
    'wi-night-cloudy': night_cloudy,
    'wi-night-cloudy-gusts': night_cloudy_gusts,
    'wi-night-cloudy-windy': night_cloudy_windy,
    'wi-night-fog': night_fog,
    'wi-night-hail': night_hail,
    'wi-night-lightning': night_lightning,
    'wi-night-partly-cloudy': night_partly_cloudy,
    'wi-night-rain': night_rain,
    'wi-night-rain-mix': night_rain_mix,
    'wi-night-rain-wind': night_rain_wind,
    'wi-night-showers': night_showers,
    'wi-night-sleet': night_sleet,
    'wi-night-sleet-storm': night_sleet_storm,
    'wi-night-snow': night_snow,
    'wi-night-snow-thunderstorm': night_snow_thunderstorm,
    'wi-night-snow-wind': night_snow_wind,
    'wi-night-sprinkle': night_sprinkle,
    'wi-night-storm-showers': night_storm_showers,
    'wi-night-thunderstorm': night_thunderstorm,
    'wi-lunar-eclipse': lunar_eclipse,
    'wi-stars': stars,
    'wi-storm-showers': storm_showers,
    'wi-thunderstorm': thunderstorm,
    'wi-night-alt-cloudy-high': night_alt_cloudy_high,
    'wi-night-cloudy-high': night_cloudy_high,
    'wi-night-alt-partly-cloudy': night_alt_partly_cloudy,
    'wi-cloud': cloud,
    'wi-cloudy': cloudy,
    'wi-cloudy-gusts': cloudy_gusts,
    'wi-cloudy-windy': cloudy_windy,
    'wi-fog': fog,
    'wi-hail': hail,
    'wi-rain': rain,
    'wi-rain-mix': rain_mix,
    'wi-rain-wind': rain_wind,
    'wi-showers': showers,
    'wi-sleet': sleet,
    'wi-snow': snow,
    'wi-sprinkle': sprinkle,
    'wi-snow-wind': snow_wind,
    'wi-smog': smog,
    'wi-smoke': smoke,
    'wi-lightning': lightning,
    'wi-raindrops': raindrops,
    'wi-raindrop': raindrop,
    'wi-dust': dust,
    'wi-snowflake-cold': snowflake_cold,
    'wi-windy': windy,
    'wi-strong-wind': strong_wind,
    'wi-sandstorm': sandstorm,
    'wi-earthquake': earthquake,
    'wi-fire': fire,
    'wi-flood': flood,
    'wi-meteor': meteor,
    'wi-tsunami': tsunami,
    'wi-volcano': volcano,
    'wi-hurricane': hurricane,
    'wi-tornado': tornado,
    'wi-small-craft-advisory': small_craft_advisory,
    'wi-gale-warning': gale_warning,
    'wi-storm-warning': storm_warning,
    'wi-hurricane-warning': hurricane_warning,
    'wi-wind-direction': wind_direction,
    'wi-alien': alien,
    'wi-celsius': celsius,
    'wi-fahrenheit': fahrenheit,
    'wi-degrees': degrees,
    'wi-thermometer': thermometer,
    'wi-thermometer-exterior': thermometer_exterior,
    'wi-thermometer-internal': thermometer_internal,
    'wi-cloud-down': cloud_down,
    'wi-cloud-up': cloud_up,
    'wi-cloud-refresh': cloud_refresh,
    'wi-horizon': horizon,
    'wi-horizon-alt': horizon_alt,
    'wi-sunrise': sunrise,
    'wi-sunset': sunset,
    'wi-moonrise': moonrise,
    'wi-moonset': moonset,
    'wi-refresh': refresh,
    'wi-refresh-alt': refresh_alt,
    'wi-umbrella': umbrella,
    'wi-barometer': barometer,
    'wi-humidity': humidity,
    'wi-na': na,
    'wi-train': train,
    'wi-moon-new': moon_new,
    'wi-moon-waxing-crescent-1': moon_waxing_crescent_1,
    'wi-moon-waxing-crescent-2': moon_waxing_crescent_2,
    'wi-moon-waxing-crescent-3': moon_waxing_crescent_3,
    'wi-moon-waxing-crescent-4': moon_waxing_crescent_4,
    'wi-moon-waxing-crescent-5': moon_waxing_crescent_5,
    'wi-moon-waxing-crescent-6': moon_waxing_crescent_6,
    'wi-moon-first-quarter': moon_first_quarter,
    'wi-moon-waxing-gibbous-1': moon_waxing_gibbous_1,
    'wi-moon-waxing-gibbous-2': moon_waxing_gibbous_2,
    'wi-moon-waxing-gibbous-3': moon_waxing_gibbous_3,
    'wi-moon-waxing-gibbous-4': moon_waxing_gibbous_4,
    'wi-moon-waxing-gibbous-5': moon_waxing_gibbous_5,
    'wi-moon-waxing-gibbous-6': moon_waxing_gibbous_6,
    'wi-moon-full': moon_full,
    'wi-moon-waning-gibbous-1': moon_waning_gibbous_1,
    'wi-moon-waning-gibbous-2': moon_waning_gibbous_2,
    'wi-moon-waning-gibbous-3': moon_waning_gibbous_3,
    'wi-moon-waning-gibbous-4': moon_waning_gibbous_4,
    'wi-moon-waning-gibbous-5': moon_waning_gibbous_5,
    'wi-moon-waning-gibbous-6': moon_waning_gibbous_6,
    'wi-moon-third-quarter': moon_third_quarter,
    'wi-moon-waning-crescent-1': moon_waning_crescent_1,
    'wi-moon-waning-crescent-2': moon_waning_crescent_2,
    'wi-moon-waning-crescent-3': moon_waning_crescent_3,
    'wi-moon-waning-crescent-4': moon_waning_crescent_4,
    'wi-moon-waning-crescent-5': moon_waning_crescent_5,
    'wi-moon-waning-crescent-6': moon_waning_crescent_6,
    'wi-moon-alt-new': moon_alt_new,
    'wi-moon-alt-waxing-crescent-1': moon_alt_waxing_crescent_1,
    'wi-moon-alt-waxing-crescent-2': moon_alt_waxing_crescent_2,
    'wi-moon-alt-waxing-crescent-3': moon_alt_waxing_crescent_3,
    'wi-moon-alt-waxing-crescent-4': moon_alt_waxing_crescent_4,
    'wi-moon-alt-waxing-crescent-5': moon_alt_waxing_crescent_5,
    'wi-moon-alt-waxing-crescent-6': moon_alt_waxing_crescent_6,
    'wi-moon-alt-first-quarter': moon_alt_first_quarter,
    'wi-moon-alt-waxing-gibbous-1': moon_alt_waxing_gibbous_1,
    'wi-moon-alt-waxing-gibbous-2': moon_alt_waxing_gibbous_2,
    'wi-moon-alt-waxing-gibbous-3': moon_alt_waxing_gibbous_3,
    'wi-moon-alt-waxing-gibbous-4': moon_alt_waxing_gibbous_4,
    'wi-moon-alt-waxing-gibbous-5': moon_alt_waxing_gibbous_5,
    'wi-moon-alt-waxing-gibbous-6': moon_alt_waxing_gibbous_6,
    'wi-moon-alt-full': moon_alt_full,
    'wi-moon-alt-waning-gibbous-1': moon_alt_waning_gibbous_1,
    'wi-moon-alt-waning-gibbous-2': moon_alt_waning_gibbous_2,
    'wi-moon-alt-waning-gibbous-3': moon_alt_waning_gibbous_3,
    'wi-moon-alt-waning-gibbous-4': moon_alt_waning_gibbous_4,
    'wi-moon-alt-waning-gibbous-5': moon_alt_waning_gibbous_5,
    'wi-moon-alt-waning-gibbous-6': moon_alt_waning_gibbous_6,
    'wi-moon-alt-third-quarter': moon_alt_third_quarter,
    'wi-moon-alt-waning-crescent-1': moon_alt_waning_crescent_1,
    'wi-moon-alt-waning-crescent-2': moon_alt_waning_crescent_2,
    'wi-moon-alt-waning-crescent-3': moon_alt_waning_crescent_3,
    'wi-moon-alt-waning-crescent-4': moon_alt_waning_crescent_4,
    'wi-moon-alt-waning-crescent-5': moon_alt_waning_crescent_5,
    'wi-moon-alt-waning-crescent-6': moon_alt_waning_crescent_6,
    'wi-time-1': time_1,
    'wi-time-2': time_2,
    'wi-time-3': time_3,
    'wi-time-4': time_4,
    'wi-time-5': time_5,
    'wi-time-6': time_6,
    'wi-time-7': time_7,
    'wi-time-8': time_8,
    'wi-time-9': time_9,
    'wi-time-10': time_10,
    'wi-time-11': time_11,
    'wi-time-12': time_12,
    'wi-direction-up': direction_up,
    'wi-direction-up-right': direction_up_right,
    'wi-direction-right': direction_right,
    'wi-direction-down-right': direction_down_right,
    'wi-direction-down': direction_down,
    'wi-direction-down-left': direction_down_left,
    'wi-direction-left': direction_left,
    'wi-direction-up-left': direction_up_left,
    'wi-wind-beaufort-0': wind_beaufort_0,
    'wi-wind-beaufort-1': wind_beaufort_1,
    'wi-wind-beaufort-2': wind_beaufort_2,
    'wi-wind-beaufort-3': wind_beaufort_3,
    'wi-wind-beaufort-4': wind_beaufort_4,
    'wi-wind-beaufort-5': wind_beaufort_5,
    'wi-wind-beaufort-6': wind_beaufort_6,
    'wi-wind-beaufort-7': wind_beaufort_7,
    'wi-wind-beaufort-8': wind_beaufort_8,
    'wi-wind-beaufort-9': wind_beaufort_9,
    'wi-wind-beaufort-10': wind_beaufort_10,
    'wi-wind-beaufort-11': wind_beaufort_11,
    'wi-wind-beaufort-12': wind_beaufort_12,
    'wind': wind,
    'wind-deg-0': wind_deg_0,
    'wind-deg-45': wind_deg_45,
    'wind-deg-90': wind_deg_90,
    'wind-deg-135': wind_deg_135,
    'wind-deg-180': wind_deg_180,
    'wind-deg-225': wind_deg_225,
    'wind-deg-270': wind_deg_270,
    'wind-deg-315': wind_deg_315,
  };
}
