/// GENERATED CODE
/// This file is auto-generated by the 'scrape_icons' script, and should not be modified by hand.
/// See the README.md for more information.
/// Generated on Tue Jul 16 2019 21:35:35 GMT-0400 (Eastern Daylight Time)
/// Using version: __v2.0.10__ of WeatherIcons

import 'package:flutter/material.dart';

/// All of WeatherIcons in the form of static [IconData] variables.
///
/// See [WeatherIcons](https://erikflowers.github.io/weather-icons/) for more info.
///
/// For getting a rotated wind icon, you can use [WindIcon] widget.
///
/// Sample Usage:
///
///     IconButton(
///       icon: new Icon(WeatherIcons.rain),
///       onPressed: () { print("Hello World"); }
///     );
class WeatherIcons {
  static const IconData day_sunny = const _Icon(0xf00d);
  static const IconData day_cloudy = const _Icon(0xf002);
  static const IconData day_cloudy_gusts = const _Icon(0xf000);
  static const IconData day_cloudy_windy = const _Icon(0xf001);
  static const IconData day_fog = const _Icon(0xf003);
  static const IconData day_hail = const _Icon(0xf004);
  static const IconData day_haze = const _Icon(0xf0b6);
  static const IconData day_lightning = const _Icon(0xf005);
  static const IconData day_rain = const _Icon(0xf008);
  static const IconData day_rain_mix = const _Icon(0xf006);
  static const IconData day_rain_wind = const _Icon(0xf007);
  static const IconData day_showers = const _Icon(0xf009);
  static const IconData day_sleet = const _Icon(0xf0b2);
  static const IconData day_sleet_storm = const _Icon(0xf068);
  static const IconData day_snow = const _Icon(0xf00a);
  static const IconData day_snow_thunderstorm = const _Icon(0xf06b);
  static const IconData day_snow_wind = const _Icon(0xf065);
  static const IconData day_sprinkle = const _Icon(0xf00b);
  static const IconData day_storm_showers = const _Icon(0xf00e);
  static const IconData day_sunny_overcast = const _Icon(0xf00c);
  static const IconData day_thunderstorm = const _Icon(0xf010);
  static const IconData day_windy = const _Icon(0xf085);
  static const IconData solar_eclipse = const _Icon(0xf06e);
  static const IconData hot = const _Icon(0xf072);
  static const IconData day_cloudy_high = const _Icon(0xf07d);
  static const IconData day_light_wind = const _Icon(0xf0c4);
  static const IconData night_clear = const _Icon(0xf02e);
  static const IconData night_alt_cloudy = const _Icon(0xf086);
  static const IconData night_alt_cloudy_gusts = const _Icon(0xf022);
  static const IconData night_alt_cloudy_windy = const _Icon(0xf023);
  static const IconData night_alt_hail = const _Icon(0xf024);
  static const IconData night_alt_lightning = const _Icon(0xf025);
  static const IconData night_alt_rain = const _Icon(0xf028);
  static const IconData night_alt_rain_mix = const _Icon(0xf026);
  static const IconData night_alt_rain_wind = const _Icon(0xf027);
  static const IconData night_alt_showers = const _Icon(0xf029);
  static const IconData night_alt_sleet = const _Icon(0xf0b4);
  static const IconData night_alt_sleet_storm = const _Icon(0xf06a);
  static const IconData night_alt_snow = const _Icon(0xf02a);
  static const IconData night_alt_snow_thunderstorm = const _Icon(0xf06d);
  static const IconData night_alt_snow_wind = const _Icon(0xf067);
  static const IconData night_alt_sprinkle = const _Icon(0xf02b);
  static const IconData night_alt_storm_showers = const _Icon(0xf02c);
  static const IconData night_alt_thunderstorm = const _Icon(0xf02d);
  static const IconData night_cloudy = const _Icon(0xf031);
  static const IconData night_cloudy_gusts = const _Icon(0xf02f);
  static const IconData night_cloudy_windy = const _Icon(0xf030);
  static const IconData night_fog = const _Icon(0xf04a);
  static const IconData night_hail = const _Icon(0xf032);
  static const IconData night_lightning = const _Icon(0xf033);
  static const IconData night_partly_cloudy = const _Icon(0xf083);
  static const IconData night_rain = const _Icon(0xf036);
  static const IconData night_rain_mix = const _Icon(0xf034);
  static const IconData night_rain_wind = const _Icon(0xf035);
  static const IconData night_showers = const _Icon(0xf037);
  static const IconData night_sleet = const _Icon(0xf0b3);
  static const IconData night_sleet_storm = const _Icon(0xf069);
  static const IconData night_snow = const _Icon(0xf038);
  static const IconData night_snow_thunderstorm = const _Icon(0xf06c);
  static const IconData night_snow_wind = const _Icon(0xf066);
  static const IconData night_sprinkle = const _Icon(0xf039);
  static const IconData night_storm_showers = const _Icon(0xf03a);
  static const IconData night_thunderstorm = const _Icon(0xf03b);
  static const IconData lunar_eclipse = const _Icon(0xf070);
  static const IconData stars = const _Icon(0xf077);
  static const IconData storm_showers = const _Icon(0xf01d);
  static const IconData thunderstorm = const _Icon(0xf01e);
  static const IconData night_alt_cloudy_high = const _Icon(0xf07e);
  static const IconData night_cloudy_high = const _Icon(0xf080);
  static const IconData night_alt_partly_cloudy = const _Icon(0xf081);
  static const IconData cloud = const _Icon(0xf041);
  static const IconData cloudy = const _Icon(0xf013);
  static const IconData cloudy_gusts = const _Icon(0xf011);
  static const IconData cloudy_windy = const _Icon(0xf012);
  static const IconData fog = const _Icon(0xf014);
  static const IconData hail = const _Icon(0xf015);
  static const IconData rain = const _Icon(0xf019);
  static const IconData rain_mix = const _Icon(0xf017);
  static const IconData rain_wind = const _Icon(0xf018);
  static const IconData showers = const _Icon(0xf01a);
  static const IconData sleet = const _Icon(0xf0b5);
  static const IconData snow = const _Icon(0xf01b);
  static const IconData sprinkle = const _Icon(0xf01c);
  static const IconData snow_wind = const _Icon(0xf064);
  static const IconData smog = const _Icon(0xf074);
  static const IconData smoke = const _Icon(0xf062);
  static const IconData lightning = const _Icon(0xf016);
  static const IconData raindrops = const _Icon(0xf04e);
  static const IconData raindrop = const _Icon(0xf078);
  static const IconData dust = const _Icon(0xf063);
  static const IconData snowflake_cold = const _Icon(0xf076);
  static const IconData windy = const _Icon(0xf021);
  static const IconData strong_wind = const _Icon(0xf050);
  static const IconData sandstorm = const _Icon(0xf082);
  static const IconData earthquake = const _Icon(0xf0c6);
  static const IconData fire = const _Icon(0xf0c7);
  static const IconData flood = const _Icon(0xf07c);
  static const IconData meteor = const _Icon(0xf071);
  static const IconData tsunami = const _Icon(0xf0c5);
  static const IconData volcano = const _Icon(0xf0c8);
  static const IconData hurricane = const _Icon(0xf073);
  static const IconData tornado = const _Icon(0xf056);
  static const IconData small_craft_advisory = const _Icon(0xf0cc);
  static const IconData gale_warning = const _Icon(0xf0cd);
  static const IconData storm_warning = const _Icon(0xf0ce);
  static const IconData hurricane_warning = const _Icon(0xf0cf);
  static const IconData wind_direction = const _Icon(0xf0b1);
  static const IconData alien = const _Icon(0xf075);
  static const IconData celsius = const _Icon(0xf03c);
  static const IconData fahrenheit = const _Icon(0xf045);
  static const IconData degrees = const _Icon(0xf042);
  static const IconData thermometer = const _Icon(0xf055);
  static const IconData thermometer_exterior = const _Icon(0xf053);
  static const IconData thermometer_internal = const _Icon(0xf054);
  static const IconData cloud_down = const _Icon(0xf03d);
  static const IconData cloud_up = const _Icon(0xf040);
  static const IconData cloud_refresh = const _Icon(0xf03e);
  static const IconData horizon = const _Icon(0xf047);
  static const IconData horizon_alt = const _Icon(0xf046);
  static const IconData sunrise = const _Icon(0xf051);
  static const IconData sunset = const _Icon(0xf052);
  static const IconData moonrise = const _Icon(0xf0c9);
  static const IconData moonset = const _Icon(0xf0ca);
  static const IconData refresh = const _Icon(0xf04c);
  static const IconData refresh_alt = const _Icon(0xf04b);
  static const IconData umbrella = const _Icon(0xf084);
  static const IconData barometer = const _Icon(0xf079);
  static const IconData humidity = const _Icon(0xf07a);
  static const IconData na = const _Icon(0xf07b);
  static const IconData train = const _Icon(0xf0cb);
  static const IconData moon_new = const _Icon(0xf095);
  static const IconData moon_waxing_crescent_1 = const _Icon(0xf096);
  static const IconData moon_waxing_crescent_2 = const _Icon(0xf097);
  static const IconData moon_waxing_crescent_3 = const _Icon(0xf098);
  static const IconData moon_waxing_crescent_4 = const _Icon(0xf099);
  static const IconData moon_waxing_crescent_5 = const _Icon(0xf09a);
  static const IconData moon_waxing_crescent_6 = const _Icon(0xf09b);
  static const IconData moon_first_quarter = const _Icon(0xf09c);
  static const IconData moon_waxing_gibbous_1 = const _Icon(0xf09d);
  static const IconData moon_waxing_gibbous_2 = const _Icon(0xf09e);
  static const IconData moon_waxing_gibbous_3 = const _Icon(0xf09f);
  static const IconData moon_waxing_gibbous_4 = const _Icon(0xf0a0);
  static const IconData moon_waxing_gibbous_5 = const _Icon(0xf0a1);
  static const IconData moon_waxing_gibbous_6 = const _Icon(0xf0a2);
  static const IconData moon_full = const _Icon(0xf0a3);
  static const IconData moon_waning_gibbous_1 = const _Icon(0xf0a4);
  static const IconData moon_waning_gibbous_2 = const _Icon(0xf0a5);
  static const IconData moon_waning_gibbous_3 = const _Icon(0xf0a6);
  static const IconData moon_waning_gibbous_4 = const _Icon(0xf0a7);
  static const IconData moon_waning_gibbous_5 = const _Icon(0xf0a8);
  static const IconData moon_waning_gibbous_6 = const _Icon(0xf0a9);
  static const IconData moon_third_quarter = const _Icon(0xf0aa);
  static const IconData moon_waning_crescent_1 = const _Icon(0xf0ab);
  static const IconData moon_waning_crescent_2 = const _Icon(0xf0ac);
  static const IconData moon_waning_crescent_3 = const _Icon(0xf0ad);
  static const IconData moon_waning_crescent_4 = const _Icon(0xf0ae);
  static const IconData moon_waning_crescent_5 = const _Icon(0xf0af);
  static const IconData moon_waning_crescent_6 = const _Icon(0xf0b0);
  static const IconData moon_alt_new = const _Icon(0xf0eb);
  static const IconData moon_alt_waxing_crescent_1 = const _Icon(0xf0d0);
  static const IconData moon_alt_waxing_crescent_2 = const _Icon(0xf0d1);
  static const IconData moon_alt_waxing_crescent_3 = const _Icon(0xf0d2);
  static const IconData moon_alt_waxing_crescent_4 = const _Icon(0xf0d3);
  static const IconData moon_alt_waxing_crescent_5 = const _Icon(0xf0d4);
  static const IconData moon_alt_waxing_crescent_6 = const _Icon(0xf0d5);
  static const IconData moon_alt_first_quarter = const _Icon(0xf0d6);
  static const IconData moon_alt_waxing_gibbous_1 = const _Icon(0xf0d7);
  static const IconData moon_alt_waxing_gibbous_2 = const _Icon(0xf0d8);
  static const IconData moon_alt_waxing_gibbous_3 = const _Icon(0xf0d9);
  static const IconData moon_alt_waxing_gibbous_4 = const _Icon(0xf0da);
  static const IconData moon_alt_waxing_gibbous_5 = const _Icon(0xf0db);
  static const IconData moon_alt_waxing_gibbous_6 = const _Icon(0xf0dc);
  static const IconData moon_alt_full = const _Icon(0xf0dd);
  static const IconData moon_alt_waning_gibbous_1 = const _Icon(0xf0de);
  static const IconData moon_alt_waning_gibbous_2 = const _Icon(0xf0df);
  static const IconData moon_alt_waning_gibbous_3 = const _Icon(0xf0e0);
  static const IconData moon_alt_waning_gibbous_4 = const _Icon(0xf0e1);
  static const IconData moon_alt_waning_gibbous_5 = const _Icon(0xf0e2);
  static const IconData moon_alt_waning_gibbous_6 = const _Icon(0xf0e3);
  static const IconData moon_alt_third_quarter = const _Icon(0xf0e4);
  static const IconData moon_alt_waning_crescent_1 = const _Icon(0xf0e5);
  static const IconData moon_alt_waning_crescent_2 = const _Icon(0xf0e6);
  static const IconData moon_alt_waning_crescent_3 = const _Icon(0xf0e7);
  static const IconData moon_alt_waning_crescent_4 = const _Icon(0xf0e8);
  static const IconData moon_alt_waning_crescent_5 = const _Icon(0xf0e9);
  static const IconData moon_alt_waning_crescent_6 = const _Icon(0xf0ea);
  static const IconData time_1 = const _Icon(0xf08a);
  static const IconData time_2 = const _Icon(0xf08b);
  static const IconData time_3 = const _Icon(0xf08c);
  static const IconData time_4 = const _Icon(0xf08d);
  static const IconData time_5 = const _Icon(0xf08e);
  static const IconData time_6 = const _Icon(0xf08f);
  static const IconData time_7 = const _Icon(0xf090);
  static const IconData time_8 = const _Icon(0xf091);
  static const IconData time_9 = const _Icon(0xf092);
  static const IconData time_10 = const _Icon(0xf093);
  static const IconData time_11 = const _Icon(0xf094);
  static const IconData time_12 = const _Icon(0xf089);
  static const IconData direction_up = const _Icon(0xf058);
  static const IconData direction_up_right = const _Icon(0xf057);
  static const IconData direction_right = const _Icon(0xf04d);
  static const IconData direction_down_right = const _Icon(0xf088);
  static const IconData direction_down = const _Icon(0xf044);
  static const IconData direction_down_left = const _Icon(0xf043);
  static const IconData direction_left = const _Icon(0xf048);
  static const IconData direction_up_left = const _Icon(0xf087);
  static const IconData wind_beaufort_0 = const _Icon(0xf0b7);
  static const IconData wind_beaufort_1 = const _Icon(0xf0b8);
  static const IconData wind_beaufort_2 = const _Icon(0xf0b9);
  static const IconData wind_beaufort_3 = const _Icon(0xf0ba);
  static const IconData wind_beaufort_4 = const _Icon(0xf0bb);
  static const IconData wind_beaufort_5 = const _Icon(0xf0bc);
  static const IconData wind_beaufort_6 = const _Icon(0xf0bd);
  static const IconData wind_beaufort_7 = const _Icon(0xf0be);
  static const IconData wind_beaufort_8 = const _Icon(0xf0bf);
  static const IconData wind_beaufort_9 = const _Icon(0xf0c0);
  static const IconData wind_beaufort_10 = const _Icon(0xf0c1);
  static const IconData wind_beaufort_11 = const _Icon(0xf0c2);
  static const IconData wind_beaufort_12 = const _Icon(0xf0c3);
  static const IconData wind = const _Icon(0xf0b1);

  /// Get the matching [IconData] from the WeatherIcon name.
  /// Pass in a [fallback] or else it will throw.
  ///
  /// See [WeatherIcons](https://erikflowers.github.io/weather-icons/) for more info.
  ///
  /// Sample Usage:
  ///
  ///     IconButton(
  ///       icon: new Icon(WeatherIcons.fromName('wi-day-sunny')),
  ///       onPressed: () { print("Hello World"); }
  ///     );
  static IconData fromName(
    String name, {
    IconData fallback,
  }) {
    final target = name.replaceAll('_', '-');
    if (!_all.containsKey(target) && fallback == null) {
      throw UnsupportedError('Unsupported icon $name, with no fallback');
    }

    return _Icon(_all[target]) ?? fallback;
  }

  static const Map<String, int> _all = {
    'wi-day-sunny': 0xf00d,
    'wi-day-cloudy': 0xf002,
    'wi-day-cloudy-gusts': 0xf000,
    'wi-day-cloudy-windy': 0xf001,
    'wi-day-fog': 0xf003,
    'wi-day-hail': 0xf004,
    'wi-day-haze': 0xf0b6,
    'wi-day-lightning': 0xf005,
    'wi-day-rain': 0xf008,
    'wi-day-rain-mix': 0xf006,
    'wi-day-rain-wind': 0xf007,
    'wi-day-showers': 0xf009,
    'wi-day-sleet': 0xf0b2,
    'wi-day-sleet-storm': 0xf068,
    'wi-day-snow': 0xf00a,
    'wi-day-snow-thunderstorm': 0xf06b,
    'wi-day-snow-wind': 0xf065,
    'wi-day-sprinkle': 0xf00b,
    'wi-day-storm-showers': 0xf00e,
    'wi-day-sunny-overcast': 0xf00c,
    'wi-day-thunderstorm': 0xf010,
    'wi-day-windy': 0xf085,
    'wi-solar-eclipse': 0xf06e,
    'wi-hot': 0xf072,
    'wi-day-cloudy-high': 0xf07d,
    'wi-day-light-wind': 0xf0c4,
    'wi-night-clear': 0xf02e,
    'wi-night-alt-cloudy': 0xf086,
    'wi-night-alt-cloudy-gusts': 0xf022,
    'wi-night-alt-cloudy-windy': 0xf023,
    'wi-night-alt-hail': 0xf024,
    'wi-night-alt-lightning': 0xf025,
    'wi-night-alt-rain': 0xf028,
    'wi-night-alt-rain-mix': 0xf026,
    'wi-night-alt-rain-wind': 0xf027,
    'wi-night-alt-showers': 0xf029,
    'wi-night-alt-sleet': 0xf0b4,
    'wi-night-alt-sleet-storm': 0xf06a,
    'wi-night-alt-snow': 0xf02a,
    'wi-night-alt-snow-thunderstorm': 0xf06d,
    'wi-night-alt-snow-wind': 0xf067,
    'wi-night-alt-sprinkle': 0xf02b,
    'wi-night-alt-storm-showers': 0xf02c,
    'wi-night-alt-thunderstorm': 0xf02d,
    'wi-night-cloudy': 0xf031,
    'wi-night-cloudy-gusts': 0xf02f,
    'wi-night-cloudy-windy': 0xf030,
    'wi-night-fog': 0xf04a,
    'wi-night-hail': 0xf032,
    'wi-night-lightning': 0xf033,
    'wi-night-partly-cloudy': 0xf083,
    'wi-night-rain': 0xf036,
    'wi-night-rain-mix': 0xf034,
    'wi-night-rain-wind': 0xf035,
    'wi-night-showers': 0xf037,
    'wi-night-sleet': 0xf0b3,
    'wi-night-sleet-storm': 0xf069,
    'wi-night-snow': 0xf038,
    'wi-night-snow-thunderstorm': 0xf06c,
    'wi-night-snow-wind': 0xf066,
    'wi-night-sprinkle': 0xf039,
    'wi-night-storm-showers': 0xf03a,
    'wi-night-thunderstorm': 0xf03b,
    'wi-lunar-eclipse': 0xf070,
    'wi-stars': 0xf077,
    'wi-storm-showers': 0xf01d,
    'wi-thunderstorm': 0xf01e,
    'wi-night-alt-cloudy-high': 0xf07e,
    'wi-night-cloudy-high': 0xf080,
    'wi-night-alt-partly-cloudy': 0xf081,
    'wi-cloud': 0xf041,
    'wi-cloudy': 0xf013,
    'wi-cloudy-gusts': 0xf011,
    'wi-cloudy-windy': 0xf012,
    'wi-fog': 0xf014,
    'wi-hail': 0xf015,
    'wi-rain': 0xf019,
    'wi-rain-mix': 0xf017,
    'wi-rain-wind': 0xf018,
    'wi-showers': 0xf01a,
    'wi-sleet': 0xf0b5,
    'wi-snow': 0xf01b,
    'wi-sprinkle': 0xf01c,
    'wi-snow-wind': 0xf064,
    'wi-smog': 0xf074,
    'wi-smoke': 0xf062,
    'wi-lightning': 0xf016,
    'wi-raindrops': 0xf04e,
    'wi-raindrop': 0xf078,
    'wi-dust': 0xf063,
    'wi-snowflake-cold': 0xf076,
    'wi-windy': 0xf021,
    'wi-strong-wind': 0xf050,
    'wi-sandstorm': 0xf082,
    'wi-earthquake': 0xf0c6,
    'wi-fire': 0xf0c7,
    'wi-flood': 0xf07c,
    'wi-meteor': 0xf071,
    'wi-tsunami': 0xf0c5,
    'wi-volcano': 0xf0c8,
    'wi-hurricane': 0xf073,
    'wi-tornado': 0xf056,
    'wi-small-craft-advisory': 0xf0cc,
    'wi-gale-warning': 0xf0cd,
    'wi-storm-warning': 0xf0ce,
    'wi-hurricane-warning': 0xf0cf,
    'wi-wind-direction': 0xf0b1,
    'wi-alien': 0xf075,
    'wi-celsius': 0xf03c,
    'wi-fahrenheit': 0xf045,
    'wi-degrees': 0xf042,
    'wi-thermometer': 0xf055,
    'wi-thermometer-exterior': 0xf053,
    'wi-thermometer-internal': 0xf054,
    'wi-cloud-down': 0xf03d,
    'wi-cloud-up': 0xf040,
    'wi-cloud-refresh': 0xf03e,
    'wi-horizon': 0xf047,
    'wi-horizon-alt': 0xf046,
    'wi-sunrise': 0xf051,
    'wi-sunset': 0xf052,
    'wi-moonrise': 0xf0c9,
    'wi-moonset': 0xf0ca,
    'wi-refresh': 0xf04c,
    'wi-refresh-alt': 0xf04b,
    'wi-umbrella': 0xf084,
    'wi-barometer': 0xf079,
    'wi-humidity': 0xf07a,
    'wi-na': 0xf07b,
    'wi-train': 0xf0cb,
    'wi-moon-new': 0xf095,
    'wi-moon-waxing-crescent-1': 0xf096,
    'wi-moon-waxing-crescent-2': 0xf097,
    'wi-moon-waxing-crescent-3': 0xf098,
    'wi-moon-waxing-crescent-4': 0xf099,
    'wi-moon-waxing-crescent-5': 0xf09a,
    'wi-moon-waxing-crescent-6': 0xf09b,
    'wi-moon-first-quarter': 0xf09c,
    'wi-moon-waxing-gibbous-1': 0xf09d,
    'wi-moon-waxing-gibbous-2': 0xf09e,
    'wi-moon-waxing-gibbous-3': 0xf09f,
    'wi-moon-waxing-gibbous-4': 0xf0a0,
    'wi-moon-waxing-gibbous-5': 0xf0a1,
    'wi-moon-waxing-gibbous-6': 0xf0a2,
    'wi-moon-full': 0xf0a3,
    'wi-moon-waning-gibbous-1': 0xf0a4,
    'wi-moon-waning-gibbous-2': 0xf0a5,
    'wi-moon-waning-gibbous-3': 0xf0a6,
    'wi-moon-waning-gibbous-4': 0xf0a7,
    'wi-moon-waning-gibbous-5': 0xf0a8,
    'wi-moon-waning-gibbous-6': 0xf0a9,
    'wi-moon-third-quarter': 0xf0aa,
    'wi-moon-waning-crescent-1': 0xf0ab,
    'wi-moon-waning-crescent-2': 0xf0ac,
    'wi-moon-waning-crescent-3': 0xf0ad,
    'wi-moon-waning-crescent-4': 0xf0ae,
    'wi-moon-waning-crescent-5': 0xf0af,
    'wi-moon-waning-crescent-6': 0xf0b0,
    'wi-moon-alt-new': 0xf0eb,
    'wi-moon-alt-waxing-crescent-1': 0xf0d0,
    'wi-moon-alt-waxing-crescent-2': 0xf0d1,
    'wi-moon-alt-waxing-crescent-3': 0xf0d2,
    'wi-moon-alt-waxing-crescent-4': 0xf0d3,
    'wi-moon-alt-waxing-crescent-5': 0xf0d4,
    'wi-moon-alt-waxing-crescent-6': 0xf0d5,
    'wi-moon-alt-first-quarter': 0xf0d6,
    'wi-moon-alt-waxing-gibbous-1': 0xf0d7,
    'wi-moon-alt-waxing-gibbous-2': 0xf0d8,
    'wi-moon-alt-waxing-gibbous-3': 0xf0d9,
    'wi-moon-alt-waxing-gibbous-4': 0xf0da,
    'wi-moon-alt-waxing-gibbous-5': 0xf0db,
    'wi-moon-alt-waxing-gibbous-6': 0xf0dc,
    'wi-moon-alt-full': 0xf0dd,
    'wi-moon-alt-waning-gibbous-1': 0xf0de,
    'wi-moon-alt-waning-gibbous-2': 0xf0df,
    'wi-moon-alt-waning-gibbous-3': 0xf0e0,
    'wi-moon-alt-waning-gibbous-4': 0xf0e1,
    'wi-moon-alt-waning-gibbous-5': 0xf0e2,
    'wi-moon-alt-waning-gibbous-6': 0xf0e3,
    'wi-moon-alt-third-quarter': 0xf0e4,
    'wi-moon-alt-waning-crescent-1': 0xf0e5,
    'wi-moon-alt-waning-crescent-2': 0xf0e6,
    'wi-moon-alt-waning-crescent-3': 0xf0e7,
    'wi-moon-alt-waning-crescent-4': 0xf0e8,
    'wi-moon-alt-waning-crescent-5': 0xf0e9,
    'wi-moon-alt-waning-crescent-6': 0xf0ea,
    'wi-time-1': 0xf08a,
    'wi-time-2': 0xf08b,
    'wi-time-3': 0xf08c,
    'wi-time-4': 0xf08d,
    'wi-time-5': 0xf08e,
    'wi-time-6': 0xf08f,
    'wi-time-7': 0xf090,
    'wi-time-8': 0xf091,
    'wi-time-9': 0xf092,
    'wi-time-10': 0xf093,
    'wi-time-11': 0xf094,
    'wi-time-12': 0xf089,
    'wi-direction-up': 0xf058,
    'wi-direction-up-right': 0xf057,
    'wi-direction-right': 0xf04d,
    'wi-direction-down-right': 0xf088,
    'wi-direction-down': 0xf044,
    'wi-direction-down-left': 0xf043,
    'wi-direction-left': 0xf048,
    'wi-direction-up-left': 0xf087,
    'wi-wind-beaufort-0': 0xf0b7,
    'wi-wind-beaufort-1': 0xf0b8,
    'wi-wind-beaufort-2': 0xf0b9,
    'wi-wind-beaufort-3': 0xf0ba,
    'wi-wind-beaufort-4': 0xf0bb,
    'wi-wind-beaufort-5': 0xf0bc,
    'wi-wind-beaufort-6': 0xf0bd,
    'wi-wind-beaufort-7': 0xf0be,
    'wi-wind-beaufort-8': 0xf0bf,
    'wi-wind-beaufort-9': 0xf0c0,
    'wi-wind-beaufort-10': 0xf0c1,
    'wi-wind-beaufort-11': 0xf0c2,
    'wi-wind-beaufort-12': 0xf0c3,
    'wind': 0xf0b1,
  };
}

class _Icon extends IconData {
  const _Icon(int value)
      : super(
          value,
          fontFamily: 'WeatherIcons',
          fontPackage: 'weather_icons',
        );
}
