/// GENERATED CODE
/// This file is auto-generated by the 'scrape_icons' script, and should not be modified by hand.
/// See the README.md for more information.
/// Generated on Fri Jul 19 2019 19:09:24 GMT-0400 (Eastern Daylight Time)

import 'package:flutter/material.dart';

import 'package:weather_icons/src/util/wi_data.dart';

/// All of WeatherIcons in the form of static [IconData] variables.
///
/// See [WeatherIcons](https://erikflowers.github.io/weather-icons/) for more info.
///
/// For getting a rotated wind icon, you can use [WindIcon] widget.
///
/// Sample Usage:
///
///     IconButton(
///       icon: new Icon(WeatherIcons.rain),
///       onPressed: () { print("Hello World"); }
///     );
class WeatherIcons {
  /// [IconData] for 'wi-day-sunny' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_sunny = const WIData(0xf00d);

  /// [IconData] for 'wi-day-cloudy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_cloudy = const WIData(0xf002);

  /// [IconData] for 'wi-day-cloudy-gusts' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_cloudy_gusts = const WIData(0xf000);

  /// [IconData] for 'wi-day-cloudy-windy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_cloudy_windy = const WIData(0xf001);

  /// [IconData] for 'wi-day-fog' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_fog = const WIData(0xf003);

  /// [IconData] for 'wi-day-hail' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_hail = const WIData(0xf004);

  /// [IconData] for 'wi-day-haze' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_haze = const WIData(0xf0b6);

  /// [IconData] for 'wi-day-lightning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_lightning = const WIData(0xf005);

  /// [IconData] for 'wi-day-rain' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_rain = const WIData(0xf008);

  /// [IconData] for 'wi-day-rain-mix' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_rain_mix = const WIData(0xf006);

  /// [IconData] for 'wi-day-rain-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_rain_wind = const WIData(0xf007);

  /// [IconData] for 'wi-day-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_showers = const WIData(0xf009);

  /// [IconData] for 'wi-day-sleet' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_sleet = const WIData(0xf0b2);

  /// [IconData] for 'wi-day-sleet-storm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_sleet_storm = const WIData(0xf068);

  /// [IconData] for 'wi-day-snow' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_snow = const WIData(0xf00a);

  /// [IconData] for 'wi-day-snow-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_snow_thunderstorm = const WIData(0xf06b);

  /// [IconData] for 'wi-day-snow-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_snow_wind = const WIData(0xf065);

  /// [IconData] for 'wi-day-sprinkle' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_sprinkle = const WIData(0xf00b);

  /// [IconData] for 'wi-day-storm-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_storm_showers = const WIData(0xf00e);

  /// [IconData] for 'wi-day-sunny-overcast' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_sunny_overcast = const WIData(0xf00c);

  /// [IconData] for 'wi-day-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_thunderstorm = const WIData(0xf010);

  /// [IconData] for 'wi-day-windy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_windy = const WIData(0xf085);

  /// [IconData] for 'wi-solar-eclipse' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData solar_eclipse = const WIData(0xf06e);

  /// [IconData] for 'wi-hot' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData hot = const WIData(0xf072);

  /// [IconData] for 'wi-day-cloudy-high' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_cloudy_high = const WIData(0xf07d);

  /// [IconData] for 'wi-day-light-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData day_light_wind = const WIData(0xf0c4);

  /// [IconData] for 'wi-night-clear' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_clear = const WIData(0xf02e);

  /// [IconData] for 'wi-night-alt-cloudy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_cloudy = const WIData(0xf086);

  /// [IconData] for 'wi-night-alt-cloudy-gusts' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_cloudy_gusts = const WIData(0xf022);

  /// [IconData] for 'wi-night-alt-cloudy-windy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_cloudy_windy = const WIData(0xf023);

  /// [IconData] for 'wi-night-alt-hail' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_hail = const WIData(0xf024);

  /// [IconData] for 'wi-night-alt-lightning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_lightning = const WIData(0xf025);

  /// [IconData] for 'wi-night-alt-rain' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_rain = const WIData(0xf028);

  /// [IconData] for 'wi-night-alt-rain-mix' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_rain_mix = const WIData(0xf026);

  /// [IconData] for 'wi-night-alt-rain-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_rain_wind = const WIData(0xf027);

  /// [IconData] for 'wi-night-alt-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_showers = const WIData(0xf029);

  /// [IconData] for 'wi-night-alt-sleet' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_sleet = const WIData(0xf0b4);

  /// [IconData] for 'wi-night-alt-sleet-storm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_sleet_storm = const WIData(0xf06a);

  /// [IconData] for 'wi-night-alt-snow' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_snow = const WIData(0xf02a);

  /// [IconData] for 'wi-night-alt-snow-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_snow_thunderstorm = const WIData(0xf06d);

  /// [IconData] for 'wi-night-alt-snow-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_snow_wind = const WIData(0xf067);

  /// [IconData] for 'wi-night-alt-sprinkle' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_sprinkle = const WIData(0xf02b);

  /// [IconData] for 'wi-night-alt-storm-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_storm_showers = const WIData(0xf02c);

  /// [IconData] for 'wi-night-alt-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_thunderstorm = const WIData(0xf02d);

  /// [IconData] for 'wi-night-cloudy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_cloudy = const WIData(0xf031);

  /// [IconData] for 'wi-night-cloudy-gusts' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_cloudy_gusts = const WIData(0xf02f);

  /// [IconData] for 'wi-night-cloudy-windy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_cloudy_windy = const WIData(0xf030);

  /// [IconData] for 'wi-night-fog' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_fog = const WIData(0xf04a);

  /// [IconData] for 'wi-night-hail' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_hail = const WIData(0xf032);

  /// [IconData] for 'wi-night-lightning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_lightning = const WIData(0xf033);

  /// [IconData] for 'wi-night-partly-cloudy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_partly_cloudy = const WIData(0xf083);

  /// [IconData] for 'wi-night-rain' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_rain = const WIData(0xf036);

  /// [IconData] for 'wi-night-rain-mix' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_rain_mix = const WIData(0xf034);

  /// [IconData] for 'wi-night-rain-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_rain_wind = const WIData(0xf035);

  /// [IconData] for 'wi-night-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_showers = const WIData(0xf037);

  /// [IconData] for 'wi-night-sleet' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_sleet = const WIData(0xf0b3);

  /// [IconData] for 'wi-night-sleet-storm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_sleet_storm = const WIData(0xf069);

  /// [IconData] for 'wi-night-snow' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_snow = const WIData(0xf038);

  /// [IconData] for 'wi-night-snow-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_snow_thunderstorm = const WIData(0xf06c);

  /// [IconData] for 'wi-night-snow-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_snow_wind = const WIData(0xf066);

  /// [IconData] for 'wi-night-sprinkle' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_sprinkle = const WIData(0xf039);

  /// [IconData] for 'wi-night-storm-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_storm_showers = const WIData(0xf03a);

  /// [IconData] for 'wi-night-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_thunderstorm = const WIData(0xf03b);

  /// [IconData] for 'wi-lunar-eclipse' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData lunar_eclipse = const WIData(0xf070);

  /// [IconData] for 'wi-stars' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData stars = const WIData(0xf077);

  /// [IconData] for 'wi-storm-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData storm_showers = const WIData(0xf01d);

  /// [IconData] for 'wi-thunderstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData thunderstorm = const WIData(0xf01e);

  /// [IconData] for 'wi-night-alt-cloudy-high' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_cloudy_high = const WIData(0xf07e);

  /// [IconData] for 'wi-night-cloudy-high' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_cloudy_high = const WIData(0xf080);

  /// [IconData] for 'wi-night-alt-partly-cloudy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData night_alt_partly_cloudy = const WIData(0xf081);

  /// [IconData] for 'wi-cloud' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloud = const WIData(0xf041);

  /// [IconData] for 'wi-cloudy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloudy = const WIData(0xf013);

  /// [IconData] for 'wi-cloudy-gusts' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloudy_gusts = const WIData(0xf011);

  /// [IconData] for 'wi-cloudy-windy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloudy_windy = const WIData(0xf012);

  /// [IconData] for 'wi-fog' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData fog = const WIData(0xf014);

  /// [IconData] for 'wi-hail' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData hail = const WIData(0xf015);

  /// [IconData] for 'wi-rain' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData rain = const WIData(0xf019);

  /// [IconData] for 'wi-rain-mix' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData rain_mix = const WIData(0xf017);

  /// [IconData] for 'wi-rain-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData rain_wind = const WIData(0xf018);

  /// [IconData] for 'wi-showers' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData showers = const WIData(0xf01a);

  /// [IconData] for 'wi-sleet' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData sleet = const WIData(0xf0b5);

  /// [IconData] for 'wi-snow' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData snow = const WIData(0xf01b);

  /// [IconData] for 'wi-sprinkle' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData sprinkle = const WIData(0xf01c);

  /// [IconData] for 'wi-snow-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData snow_wind = const WIData(0xf064);

  /// [IconData] for 'wi-smog' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData smog = const WIData(0xf074);

  /// [IconData] for 'wi-smoke' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData smoke = const WIData(0xf062);

  /// [IconData] for 'wi-lightning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData lightning = const WIData(0xf016);

  /// [IconData] for 'wi-raindrops' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData raindrops = const WIData(0xf04e);

  /// [IconData] for 'wi-raindrop' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData raindrop = const WIData(0xf078);

  /// [IconData] for 'wi-dust' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData dust = const WIData(0xf063);

  /// [IconData] for 'wi-snowflake-cold' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData snowflake_cold = const WIData(0xf076);

  /// [IconData] for 'wi-windy' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData windy = const WIData(0xf021);

  /// [IconData] for 'wi-strong-wind' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData strong_wind = const WIData(0xf050);

  /// [IconData] for 'wi-sandstorm' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData sandstorm = const WIData(0xf082);

  /// [IconData] for 'wi-earthquake' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData earthquake = const WIData(0xf0c6);

  /// [IconData] for 'wi-fire' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData fire = const WIData(0xf0c7);

  /// [IconData] for 'wi-flood' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData flood = const WIData(0xf07c);

  /// [IconData] for 'wi-meteor' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData meteor = const WIData(0xf071);

  /// [IconData] for 'wi-tsunami' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData tsunami = const WIData(0xf0c5);

  /// [IconData] for 'wi-volcano' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData volcano = const WIData(0xf0c8);

  /// [IconData] for 'wi-hurricane' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData hurricane = const WIData(0xf073);

  /// [IconData] for 'wi-tornado' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData tornado = const WIData(0xf056);

  /// [IconData] for 'wi-small-craft-advisory' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData small_craft_advisory = const WIData(0xf0cc);

  /// [IconData] for 'wi-gale-warning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData gale_warning = const WIData(0xf0cd);

  /// [IconData] for 'wi-storm-warning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData storm_warning = const WIData(0xf0ce);

  /// [IconData] for 'wi-hurricane-warning' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData hurricane_warning = const WIData(0xf0cf);

  /// [IconData] for 'wi-wind-direction' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_direction = const WIData(0xf0b1);

  /// [IconData] for 'wi-alien' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData alien = const WIData(0xf075);

  /// [IconData] for 'wi-celsius' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData celsius = const WIData(0xf03c);

  /// [IconData] for 'wi-fahrenheit' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData fahrenheit = const WIData(0xf045);

  /// [IconData] for 'wi-degrees' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData degrees = const WIData(0xf042);

  /// [IconData] for 'wi-thermometer' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData thermometer = const WIData(0xf055);

  /// [IconData] for 'wi-thermometer-exterior' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData thermometer_exterior = const WIData(0xf053);

  /// [IconData] for 'wi-thermometer-internal' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData thermometer_internal = const WIData(0xf054);

  /// [IconData] for 'wi-cloud-down' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloud_down = const WIData(0xf03d);

  /// [IconData] for 'wi-cloud-up' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloud_up = const WIData(0xf040);

  /// [IconData] for 'wi-cloud-refresh' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData cloud_refresh = const WIData(0xf03e);

  /// [IconData] for 'wi-horizon' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData horizon = const WIData(0xf047);

  /// [IconData] for 'wi-horizon-alt' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData horizon_alt = const WIData(0xf046);

  /// [IconData] for 'wi-sunrise' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData sunrise = const WIData(0xf051);

  /// [IconData] for 'wi-sunset' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData sunset = const WIData(0xf052);

  /// [IconData] for 'wi-moonrise' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moonrise = const WIData(0xf0c9);

  /// [IconData] for 'wi-moonset' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moonset = const WIData(0xf0ca);

  /// [IconData] for 'wi-refresh' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData refresh = const WIData(0xf04c);

  /// [IconData] for 'wi-refresh-alt' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData refresh_alt = const WIData(0xf04b);

  /// [IconData] for 'wi-umbrella' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData umbrella = const WIData(0xf084);

  /// [IconData] for 'wi-barometer' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData barometer = const WIData(0xf079);

  /// [IconData] for 'wi-humidity' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData humidity = const WIData(0xf07a);

  /// [IconData] for 'wi-na' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData na = const WIData(0xf07b);

  /// [IconData] for 'wi-train' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData train = const WIData(0xf0cb);

  /// [IconData] for 'wi-moon-new' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_new = const WIData(0xf095);

  /// [IconData] for 'wi-moon-waxing-crescent-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_crescent_1 = const WIData(0xf096);

  /// [IconData] for 'wi-moon-waxing-crescent-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_crescent_2 = const WIData(0xf097);

  /// [IconData] for 'wi-moon-waxing-crescent-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_crescent_3 = const WIData(0xf098);

  /// [IconData] for 'wi-moon-waxing-crescent-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_crescent_4 = const WIData(0xf099);

  /// [IconData] for 'wi-moon-waxing-crescent-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_crescent_5 = const WIData(0xf09a);

  /// [IconData] for 'wi-moon-waxing-crescent-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_crescent_6 = const WIData(0xf09b);

  /// [IconData] for 'wi-moon-first-quarter' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_first_quarter = const WIData(0xf09c);

  /// [IconData] for 'wi-moon-waxing-gibbous-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_gibbous_1 = const WIData(0xf09d);

  /// [IconData] for 'wi-moon-waxing-gibbous-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_gibbous_2 = const WIData(0xf09e);

  /// [IconData] for 'wi-moon-waxing-gibbous-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_gibbous_3 = const WIData(0xf09f);

  /// [IconData] for 'wi-moon-waxing-gibbous-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_gibbous_4 = const WIData(0xf0a0);

  /// [IconData] for 'wi-moon-waxing-gibbous-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_gibbous_5 = const WIData(0xf0a1);

  /// [IconData] for 'wi-moon-waxing-gibbous-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waxing_gibbous_6 = const WIData(0xf0a2);

  /// [IconData] for 'wi-moon-full' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_full = const WIData(0xf0a3);

  /// [IconData] for 'wi-moon-waning-gibbous-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_gibbous_1 = const WIData(0xf0a4);

  /// [IconData] for 'wi-moon-waning-gibbous-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_gibbous_2 = const WIData(0xf0a5);

  /// [IconData] for 'wi-moon-waning-gibbous-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_gibbous_3 = const WIData(0xf0a6);

  /// [IconData] for 'wi-moon-waning-gibbous-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_gibbous_4 = const WIData(0xf0a7);

  /// [IconData] for 'wi-moon-waning-gibbous-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_gibbous_5 = const WIData(0xf0a8);

  /// [IconData] for 'wi-moon-waning-gibbous-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_gibbous_6 = const WIData(0xf0a9);

  /// [IconData] for 'wi-moon-third-quarter' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_third_quarter = const WIData(0xf0aa);

  /// [IconData] for 'wi-moon-waning-crescent-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_crescent_1 = const WIData(0xf0ab);

  /// [IconData] for 'wi-moon-waning-crescent-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_crescent_2 = const WIData(0xf0ac);

  /// [IconData] for 'wi-moon-waning-crescent-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_crescent_3 = const WIData(0xf0ad);

  /// [IconData] for 'wi-moon-waning-crescent-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_crescent_4 = const WIData(0xf0ae);

  /// [IconData] for 'wi-moon-waning-crescent-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_crescent_5 = const WIData(0xf0af);

  /// [IconData] for 'wi-moon-waning-crescent-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_waning_crescent_6 = const WIData(0xf0b0);

  /// [IconData] for 'wi-moon-alt-new' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_new = const WIData(0xf0eb);

  /// [IconData] for 'wi-moon-alt-waxing-crescent-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_crescent_1 = const WIData(0xf0d0);

  /// [IconData] for 'wi-moon-alt-waxing-crescent-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_crescent_2 = const WIData(0xf0d1);

  /// [IconData] for 'wi-moon-alt-waxing-crescent-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_crescent_3 = const WIData(0xf0d2);

  /// [IconData] for 'wi-moon-alt-waxing-crescent-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_crescent_4 = const WIData(0xf0d3);

  /// [IconData] for 'wi-moon-alt-waxing-crescent-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_crescent_5 = const WIData(0xf0d4);

  /// [IconData] for 'wi-moon-alt-waxing-crescent-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_crescent_6 = const WIData(0xf0d5);

  /// [IconData] for 'wi-moon-alt-first-quarter' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_first_quarter = const WIData(0xf0d6);

  /// [IconData] for 'wi-moon-alt-waxing-gibbous-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_gibbous_1 = const WIData(0xf0d7);

  /// [IconData] for 'wi-moon-alt-waxing-gibbous-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_gibbous_2 = const WIData(0xf0d8);

  /// [IconData] for 'wi-moon-alt-waxing-gibbous-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_gibbous_3 = const WIData(0xf0d9);

  /// [IconData] for 'wi-moon-alt-waxing-gibbous-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_gibbous_4 = const WIData(0xf0da);

  /// [IconData] for 'wi-moon-alt-waxing-gibbous-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_gibbous_5 = const WIData(0xf0db);

  /// [IconData] for 'wi-moon-alt-waxing-gibbous-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waxing_gibbous_6 = const WIData(0xf0dc);

  /// [IconData] for 'wi-moon-alt-full' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_full = const WIData(0xf0dd);

  /// [IconData] for 'wi-moon-alt-waning-gibbous-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_gibbous_1 = const WIData(0xf0de);

  /// [IconData] for 'wi-moon-alt-waning-gibbous-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_gibbous_2 = const WIData(0xf0df);

  /// [IconData] for 'wi-moon-alt-waning-gibbous-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_gibbous_3 = const WIData(0xf0e0);

  /// [IconData] for 'wi-moon-alt-waning-gibbous-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_gibbous_4 = const WIData(0xf0e1);

  /// [IconData] for 'wi-moon-alt-waning-gibbous-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_gibbous_5 = const WIData(0xf0e2);

  /// [IconData] for 'wi-moon-alt-waning-gibbous-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_gibbous_6 = const WIData(0xf0e3);

  /// [IconData] for 'wi-moon-alt-third-quarter' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_third_quarter = const WIData(0xf0e4);

  /// [IconData] for 'wi-moon-alt-waning-crescent-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_crescent_1 = const WIData(0xf0e5);

  /// [IconData] for 'wi-moon-alt-waning-crescent-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_crescent_2 = const WIData(0xf0e6);

  /// [IconData] for 'wi-moon-alt-waning-crescent-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_crescent_3 = const WIData(0xf0e7);

  /// [IconData] for 'wi-moon-alt-waning-crescent-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_crescent_4 = const WIData(0xf0e8);

  /// [IconData] for 'wi-moon-alt-waning-crescent-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_crescent_5 = const WIData(0xf0e9);

  /// [IconData] for 'wi-moon-alt-waning-crescent-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData moon_alt_waning_crescent_6 = const WIData(0xf0ea);

  /// [IconData] for 'wi-time-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_1 = const WIData(0xf08a);

  /// [IconData] for 'wi-time-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_2 = const WIData(0xf08b);

  /// [IconData] for 'wi-time-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_3 = const WIData(0xf08c);

  /// [IconData] for 'wi-time-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_4 = const WIData(0xf08d);

  /// [IconData] for 'wi-time-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_5 = const WIData(0xf08e);

  /// [IconData] for 'wi-time-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_6 = const WIData(0xf08f);

  /// [IconData] for 'wi-time-7' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_7 = const WIData(0xf090);

  /// [IconData] for 'wi-time-8' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_8 = const WIData(0xf091);

  /// [IconData] for 'wi-time-9' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_9 = const WIData(0xf092);

  /// [IconData] for 'wi-time-10' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_10 = const WIData(0xf093);

  /// [IconData] for 'wi-time-11' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_11 = const WIData(0xf094);

  /// [IconData] for 'wi-time-12' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData time_12 = const WIData(0xf089);

  /// [IconData] for 'wi-direction-up' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_up = const WIData(0xf058);

  /// [IconData] for 'wi-direction-up-right' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_up_right = const WIData(0xf057);

  /// [IconData] for 'wi-direction-right' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_right = const WIData(0xf04d);

  /// [IconData] for 'wi-direction-down-right' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_down_right = const WIData(0xf088);

  /// [IconData] for 'wi-direction-down' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_down = const WIData(0xf044);

  /// [IconData] for 'wi-direction-down-left' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_down_left = const WIData(0xf043);

  /// [IconData] for 'wi-direction-left' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_left = const WIData(0xf048);

  /// [IconData] for 'wi-direction-up-left' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData direction_up_left = const WIData(0xf087);

  /// [IconData] for 'wi-wind-beaufort-0' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_0 = const WIData(0xf0b7);

  /// [IconData] for 'wi-wind-beaufort-1' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_1 = const WIData(0xf0b8);

  /// [IconData] for 'wi-wind-beaufort-2' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_2 = const WIData(0xf0b9);

  /// [IconData] for 'wi-wind-beaufort-3' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_3 = const WIData(0xf0ba);

  /// [IconData] for 'wi-wind-beaufort-4' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_4 = const WIData(0xf0bb);

  /// [IconData] for 'wi-wind-beaufort-5' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_5 = const WIData(0xf0bc);

  /// [IconData] for 'wi-wind-beaufort-6' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_6 = const WIData(0xf0bd);

  /// [IconData] for 'wi-wind-beaufort-7' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_7 = const WIData(0xf0be);

  /// [IconData] for 'wi-wind-beaufort-8' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_8 = const WIData(0xf0bf);

  /// [IconData] for 'wi-wind-beaufort-9' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_9 = const WIData(0xf0c0);

  /// [IconData] for 'wi-wind-beaufort-10' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_10 = const WIData(0xf0c1);

  /// [IconData] for 'wi-wind-beaufort-11' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_11 = const WIData(0xf0c2);

  /// [IconData] for 'wi-wind-beaufort-12' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_beaufort_12 = const WIData(0xf0c3);

  /// [IconData] for the base wind icon from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  ///
  /// To achieve a rotated wind icon see [WindIcon].
  static const IconData wind = const WIData(0xf0b1);

  /// [IconData] for 'wind-deg-0' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_0 = const WIData(0xf05c);

  /// [IconData] for 'wind-deg-45' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_45 = const WIData(0xf05a);

  /// [IconData] for 'wind-deg-90' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_90 = const WIData(0xf059);

  /// [IconData] for 'wind-deg-135' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_135 = const WIData(0xf05d);

  /// [IconData] for 'wind-deg-180' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_180 = const WIData(0xf060);

  /// [IconData] for 'wind-deg-225' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_225 = const WIData(0xf05e);

  /// [IconData] for 'wind-deg-270' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_270 = const WIData(0xf061);

  /// [IconData] for 'wind-deg-315' from [WeatherIcons](https://erikflowers.github.io/weather-icons/).
  static const IconData wind_deg_315 = const WIData(0xf05b);

  /// Get the matching [IconData] from the WeatherIcon name.
  ///
  /// If you do not pass in a [fallback] then it will throw if it cannot find the icon.
  ///
  /// See [WeatherIcons](https://erikflowers.github.io/weather-icons/) for more info.
  ///
  /// Sample Usage:
  ///
  ///     IconButton(
  ///       icon: new Icon(WeatherIcons.fromString('wi-day-sunny')),
  ///       onPressed: () { print("Hello World"); }
  ///     );
  static IconData fromString(
    String name, {
    IconData fallback,
  }) {
    final target = name.replaceAll('_', '-');
    final exists = _all.containsKey(target);
    if (!exists && fallback == null) {
      throw UnsupportedError('Unsupported icon $name, with no fallback');
    }

    return exists ? WIData(_all[target]) : fallback;
  }

  static const Map<String, int> _all = {
    'wi-day-sunny': 0xf00d,
    'wi-day-cloudy': 0xf002,
    'wi-day-cloudy-gusts': 0xf000,
    'wi-day-cloudy-windy': 0xf001,
    'wi-day-fog': 0xf003,
    'wi-day-hail': 0xf004,
    'wi-day-haze': 0xf0b6,
    'wi-day-lightning': 0xf005,
    'wi-day-rain': 0xf008,
    'wi-day-rain-mix': 0xf006,
    'wi-day-rain-wind': 0xf007,
    'wi-day-showers': 0xf009,
    'wi-day-sleet': 0xf0b2,
    'wi-day-sleet-storm': 0xf068,
    'wi-day-snow': 0xf00a,
    'wi-day-snow-thunderstorm': 0xf06b,
    'wi-day-snow-wind': 0xf065,
    'wi-day-sprinkle': 0xf00b,
    'wi-day-storm-showers': 0xf00e,
    'wi-day-sunny-overcast': 0xf00c,
    'wi-day-thunderstorm': 0xf010,
    'wi-day-windy': 0xf085,
    'wi-solar-eclipse': 0xf06e,
    'wi-hot': 0xf072,
    'wi-day-cloudy-high': 0xf07d,
    'wi-day-light-wind': 0xf0c4,
    'wi-night-clear': 0xf02e,
    'wi-night-alt-cloudy': 0xf086,
    'wi-night-alt-cloudy-gusts': 0xf022,
    'wi-night-alt-cloudy-windy': 0xf023,
    'wi-night-alt-hail': 0xf024,
    'wi-night-alt-lightning': 0xf025,
    'wi-night-alt-rain': 0xf028,
    'wi-night-alt-rain-mix': 0xf026,
    'wi-night-alt-rain-wind': 0xf027,
    'wi-night-alt-showers': 0xf029,
    'wi-night-alt-sleet': 0xf0b4,
    'wi-night-alt-sleet-storm': 0xf06a,
    'wi-night-alt-snow': 0xf02a,
    'wi-night-alt-snow-thunderstorm': 0xf06d,
    'wi-night-alt-snow-wind': 0xf067,
    'wi-night-alt-sprinkle': 0xf02b,
    'wi-night-alt-storm-showers': 0xf02c,
    'wi-night-alt-thunderstorm': 0xf02d,
    'wi-night-cloudy': 0xf031,
    'wi-night-cloudy-gusts': 0xf02f,
    'wi-night-cloudy-windy': 0xf030,
    'wi-night-fog': 0xf04a,
    'wi-night-hail': 0xf032,
    'wi-night-lightning': 0xf033,
    'wi-night-partly-cloudy': 0xf083,
    'wi-night-rain': 0xf036,
    'wi-night-rain-mix': 0xf034,
    'wi-night-rain-wind': 0xf035,
    'wi-night-showers': 0xf037,
    'wi-night-sleet': 0xf0b3,
    'wi-night-sleet-storm': 0xf069,
    'wi-night-snow': 0xf038,
    'wi-night-snow-thunderstorm': 0xf06c,
    'wi-night-snow-wind': 0xf066,
    'wi-night-sprinkle': 0xf039,
    'wi-night-storm-showers': 0xf03a,
    'wi-night-thunderstorm': 0xf03b,
    'wi-lunar-eclipse': 0xf070,
    'wi-stars': 0xf077,
    'wi-storm-showers': 0xf01d,
    'wi-thunderstorm': 0xf01e,
    'wi-night-alt-cloudy-high': 0xf07e,
    'wi-night-cloudy-high': 0xf080,
    'wi-night-alt-partly-cloudy': 0xf081,
    'wi-cloud': 0xf041,
    'wi-cloudy': 0xf013,
    'wi-cloudy-gusts': 0xf011,
    'wi-cloudy-windy': 0xf012,
    'wi-fog': 0xf014,
    'wi-hail': 0xf015,
    'wi-rain': 0xf019,
    'wi-rain-mix': 0xf017,
    'wi-rain-wind': 0xf018,
    'wi-showers': 0xf01a,
    'wi-sleet': 0xf0b5,
    'wi-snow': 0xf01b,
    'wi-sprinkle': 0xf01c,
    'wi-snow-wind': 0xf064,
    'wi-smog': 0xf074,
    'wi-smoke': 0xf062,
    'wi-lightning': 0xf016,
    'wi-raindrops': 0xf04e,
    'wi-raindrop': 0xf078,
    'wi-dust': 0xf063,
    'wi-snowflake-cold': 0xf076,
    'wi-windy': 0xf021,
    'wi-strong-wind': 0xf050,
    'wi-sandstorm': 0xf082,
    'wi-earthquake': 0xf0c6,
    'wi-fire': 0xf0c7,
    'wi-flood': 0xf07c,
    'wi-meteor': 0xf071,
    'wi-tsunami': 0xf0c5,
    'wi-volcano': 0xf0c8,
    'wi-hurricane': 0xf073,
    'wi-tornado': 0xf056,
    'wi-small-craft-advisory': 0xf0cc,
    'wi-gale-warning': 0xf0cd,
    'wi-storm-warning': 0xf0ce,
    'wi-hurricane-warning': 0xf0cf,
    'wi-wind-direction': 0xf0b1,
    'wi-alien': 0xf075,
    'wi-celsius': 0xf03c,
    'wi-fahrenheit': 0xf045,
    'wi-degrees': 0xf042,
    'wi-thermometer': 0xf055,
    'wi-thermometer-exterior': 0xf053,
    'wi-thermometer-internal': 0xf054,
    'wi-cloud-down': 0xf03d,
    'wi-cloud-up': 0xf040,
    'wi-cloud-refresh': 0xf03e,
    'wi-horizon': 0xf047,
    'wi-horizon-alt': 0xf046,
    'wi-sunrise': 0xf051,
    'wi-sunset': 0xf052,
    'wi-moonrise': 0xf0c9,
    'wi-moonset': 0xf0ca,
    'wi-refresh': 0xf04c,
    'wi-refresh-alt': 0xf04b,
    'wi-umbrella': 0xf084,
    'wi-barometer': 0xf079,
    'wi-humidity': 0xf07a,
    'wi-na': 0xf07b,
    'wi-train': 0xf0cb,
    'wi-moon-new': 0xf095,
    'wi-moon-waxing-crescent-1': 0xf096,
    'wi-moon-waxing-crescent-2': 0xf097,
    'wi-moon-waxing-crescent-3': 0xf098,
    'wi-moon-waxing-crescent-4': 0xf099,
    'wi-moon-waxing-crescent-5': 0xf09a,
    'wi-moon-waxing-crescent-6': 0xf09b,
    'wi-moon-first-quarter': 0xf09c,
    'wi-moon-waxing-gibbous-1': 0xf09d,
    'wi-moon-waxing-gibbous-2': 0xf09e,
    'wi-moon-waxing-gibbous-3': 0xf09f,
    'wi-moon-waxing-gibbous-4': 0xf0a0,
    'wi-moon-waxing-gibbous-5': 0xf0a1,
    'wi-moon-waxing-gibbous-6': 0xf0a2,
    'wi-moon-full': 0xf0a3,
    'wi-moon-waning-gibbous-1': 0xf0a4,
    'wi-moon-waning-gibbous-2': 0xf0a5,
    'wi-moon-waning-gibbous-3': 0xf0a6,
    'wi-moon-waning-gibbous-4': 0xf0a7,
    'wi-moon-waning-gibbous-5': 0xf0a8,
    'wi-moon-waning-gibbous-6': 0xf0a9,
    'wi-moon-third-quarter': 0xf0aa,
    'wi-moon-waning-crescent-1': 0xf0ab,
    'wi-moon-waning-crescent-2': 0xf0ac,
    'wi-moon-waning-crescent-3': 0xf0ad,
    'wi-moon-waning-crescent-4': 0xf0ae,
    'wi-moon-waning-crescent-5': 0xf0af,
    'wi-moon-waning-crescent-6': 0xf0b0,
    'wi-moon-alt-new': 0xf0eb,
    'wi-moon-alt-waxing-crescent-1': 0xf0d0,
    'wi-moon-alt-waxing-crescent-2': 0xf0d1,
    'wi-moon-alt-waxing-crescent-3': 0xf0d2,
    'wi-moon-alt-waxing-crescent-4': 0xf0d3,
    'wi-moon-alt-waxing-crescent-5': 0xf0d4,
    'wi-moon-alt-waxing-crescent-6': 0xf0d5,
    'wi-moon-alt-first-quarter': 0xf0d6,
    'wi-moon-alt-waxing-gibbous-1': 0xf0d7,
    'wi-moon-alt-waxing-gibbous-2': 0xf0d8,
    'wi-moon-alt-waxing-gibbous-3': 0xf0d9,
    'wi-moon-alt-waxing-gibbous-4': 0xf0da,
    'wi-moon-alt-waxing-gibbous-5': 0xf0db,
    'wi-moon-alt-waxing-gibbous-6': 0xf0dc,
    'wi-moon-alt-full': 0xf0dd,
    'wi-moon-alt-waning-gibbous-1': 0xf0de,
    'wi-moon-alt-waning-gibbous-2': 0xf0df,
    'wi-moon-alt-waning-gibbous-3': 0xf0e0,
    'wi-moon-alt-waning-gibbous-4': 0xf0e1,
    'wi-moon-alt-waning-gibbous-5': 0xf0e2,
    'wi-moon-alt-waning-gibbous-6': 0xf0e3,
    'wi-moon-alt-third-quarter': 0xf0e4,
    'wi-moon-alt-waning-crescent-1': 0xf0e5,
    'wi-moon-alt-waning-crescent-2': 0xf0e6,
    'wi-moon-alt-waning-crescent-3': 0xf0e7,
    'wi-moon-alt-waning-crescent-4': 0xf0e8,
    'wi-moon-alt-waning-crescent-5': 0xf0e9,
    'wi-moon-alt-waning-crescent-6': 0xf0ea,
    'wi-time-1': 0xf08a,
    'wi-time-2': 0xf08b,
    'wi-time-3': 0xf08c,
    'wi-time-4': 0xf08d,
    'wi-time-5': 0xf08e,
    'wi-time-6': 0xf08f,
    'wi-time-7': 0xf090,
    'wi-time-8': 0xf091,
    'wi-time-9': 0xf092,
    'wi-time-10': 0xf093,
    'wi-time-11': 0xf094,
    'wi-time-12': 0xf089,
    'wi-direction-up': 0xf058,
    'wi-direction-up-right': 0xf057,
    'wi-direction-right': 0xf04d,
    'wi-direction-down-right': 0xf088,
    'wi-direction-down': 0xf044,
    'wi-direction-down-left': 0xf043,
    'wi-direction-left': 0xf048,
    'wi-direction-up-left': 0xf087,
    'wi-wind-beaufort-0': 0xf0b7,
    'wi-wind-beaufort-1': 0xf0b8,
    'wi-wind-beaufort-2': 0xf0b9,
    'wi-wind-beaufort-3': 0xf0ba,
    'wi-wind-beaufort-4': 0xf0bb,
    'wi-wind-beaufort-5': 0xf0bc,
    'wi-wind-beaufort-6': 0xf0bd,
    'wi-wind-beaufort-7': 0xf0be,
    'wi-wind-beaufort-8': 0xf0bf,
    'wi-wind-beaufort-9': 0xf0c0,
    'wi-wind-beaufort-10': 0xf0c1,
    'wi-wind-beaufort-11': 0xf0c2,
    'wi-wind-beaufort-12': 0xf0c3,
    'wind': 0xf0b1,
    'wind-deg-0': 0xf05c,
    'wind-deg-45': 0xf05a,
    'wind-deg-90': 0xf059,
    'wind-deg-135': 0xf05d,
    'wind-deg-180': 0xf060,
    'wind-deg-225': 0xf05e,
    'wind-deg-270': 0xf061,
    'wind-deg-315': 0xf05b,
  };
}
