#!/usr/bin/env node

const { resolve } = require('path')

const yargs = require('yargs').argv
const { readFile, writeFile } = require('fs-extra')
const { safeLoad, safeDump } = require('js-yaml')

const verbose = yargs.v || yargs.verbose || false
const version = yargs.ver

const log = require('./util').createLogger(verbose)

const PUBSPEC = resolve(__dirname, '..', 'pubspec.yaml')

if (!version) {
  console.error('No version was supplied!\n')
  printUsage()
  return process.exit(1)
}

start().catch(err => {
  console.error(`Unhandled error: ${err}`)
  process.exit(1)
})

async function start() {
  log.i(`Publishing version: ${version}`)
  log.i(`Using pubspec: ${PUBSPEC}`)

  const pubspec = await readPubspec()
  log.v('Read pubspec.yaml')
  log.v(JSON.stringify(pubspec, null, 2))

  await writePubspec(pubspec)

  log.i('Successfully bumped version')
  process.exit(0)
}

async function readPubspec() {
  try {
    const pubspec = await readFile(PUBSPEC, 'utf8')
    return safeLoad(pubspec)
  } catch (error) {
    console.error('Unable to read pubspec!')
    console.error(error)
    process.exit(1)
  }
}

async function writePubspec(pubspec) {
  const output = safeDump({ ...pubspec, version })

  try {
    log.v('Writing updated pubspec')
    await writeFile(PUBSPEC, output)
  } catch (error) {
    console.error('Unable to save pubspec!')
    console.error(error)
    process.exit(1)
  }
}

function printUsage() {
  log.i(
    `Usage: ${__filename} --version <version> [options]

  Publish new version of weather_icons to pub.dev.

  Options:

    --ver          Version to publish              (required)
    --help     -h  Print this usage message
    --verbose  -v  Log extra information to stdout (default: false)
    `.trimLeft(),
  )
}
